Metrics/ClassLength:
  Description: 'Avoid classes longer than 100 lines of code.'
  Enabled: false
  VersionAdded: 0.25
  CountComments: false  # count full line comments?
  Max: 100

Metrics/MethodLength:
  Description: 'Avoid methods longer than 10 lines of code.'
  StyleGuide: '#short-methods'
  Enabled: true
  VersionAdded: 0.25
  VersionChanged: 0.59.2
  CountComments: false  # count full line comments?
  Max: 30
  ExcludedMethods: []

Metrics/LineLength:
  Description: 'Limit lines to 80 characters.'
  StyleGuide: '#80-character-limits'
  Enabled: true
  VersionAdded: 0.25
  VersionChanged: 0.46
  Max: 100
  # To make it possible to copy or click on URIs in the code, we allow lines
  # containing a URI to be longer than Max.
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https
  # The IgnoreCopDirectives option causes the LineLength rule to ignore cop
  # directives like '# rubocop: enable ...' when calculating a line's length.
  IgnoreCopDirectives: false
  # The IgnoredPatterns option is a list of !ruby/regexp and/or string
  # elements. Strings will be converted to Regexp objects. A line that matches
  # any regular expression listed in this option will be ignored by LineLength.
  IgnoredPatterns: []

Style/ClassVars:
  Description: 'Avoid the use of class variables.'
  StyleGuide: '#no-class-vars'
  Enabled: false
  VersionAdded: 0.13

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false
  VersionAdded: 0.9
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
